--CREATE TABLE tb_department(id bigint generated by default as identity,  name VARCHAR(255), primary key (id));
--CREATE TABLE tb_user(id bigint generated by default as identity,  email VARCHAR(255), name VARCHAR(255), department_id bigint, primary key (id));

INSERT INTO tb_department(name) VALUES ('Gestão');
INSERT INTO tb_department(name) VALUES ('Informática');

INSERT INTO tb_user(department_id, name, email) VALUES (1, 'Maria', 'maria@gmail.com');
INSERT INTO tb_user(department_id, name, email) VALUES (1, 'Bob', 'bob@gmail.com');
INSERT INTO tb_user(department_id, name, email) VALUES (2, 'Alex', 'alex@gmail.com');
INSERT INTO tb_user(department_id, name, email) VALUES (2, 'Ana', 'ana@gmail.com');